/**
 * Jemoji Plugin for Jekyll.js
 *
 * Implements jemoji functionality
 * Converts GitHub-style emoji codes (e.g., :smile:) to emoji characters or images
 *
 * @see https://github.com/jekyll/jemoji
 */

import { Plugin } from './index';
import { Renderer } from '../core/Renderer';
import { Site } from '../core/Site';

/**
 * Common emoji mappings (GitHub-compatible subset)
 * Maps emoji names to Unicode characters
 */
const EMOJI_MAP: Record<string, string> = {
  // Smileys & People
  smile: '😄',
  smiley: '😃',
  grinning: '😀',
  grin: '😁',
  laughing: '😆',
  satisfied: '😆',
  sweat_smile: '😅',
  joy: '😂',
  rofl: '🤣',
  relaxed: '☺️',
  blush: '😊',
  innocent: '😇',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  wink: '😉',
  relieved: '😌',
  heart_eyes: '😍',
  smiling_face_with_three_hearts: '🥰',
  kissing_heart: '😘',
  kissing: '😗',
  kissing_smiling_eyes: '😙',
  kissing_closed_eyes: '😚',
  yum: '😋',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  stuck_out_tongue_closed_eyes: '😝',
  zany_face: '🤪',
  hugs: '🤗',
  thinking: '🤔',
  hand_over_mouth: '🤭',
  shushing_face: '🤫',
  lying_face: '🤥',
  flushed: '😳',
  disappointed: '😞',
  worried: '😟',
  angry: '😠',
  rage: '😡',
  pout: '😡',
  cry: '😢',
  sob: '😭',
  frowning: '😦',
  anguished: '😧',
  fearful: '😨',
  cold_sweat: '😰',
  disappointed_relieved: '😥',
  sweat: '😓',
  scream: '😱',
  tired_face: '😫',
  sleepy: '😪',
  sleeping: '😴',
  mask: '😷',
  nauseated_face: '🤢',
  sneezing_face: '🤧',
  hot_face: '🥵',
  cold_face: '🥶',
  woozy_face: '🥴',
  dizzy_face: '😵',
  exploding_head: '🤯',
  cowboy_hat_face: '🤠',
  partying_face: '🥳',
  sunglasses: '😎',
  nerd_face: '🤓',
  monocle_face: '🧐',
  confused: '😕',
  confounded: '😖',
  open_mouth: '😮',
  hushed: '😯',
  astonished: '😲',
  flushing: '😳',
  pleading_face: '🥺',
  frowning_face: '☹️',
  persevere: '😣',
  triumph: '😤',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  smirk: '😏',
  unamused: '😒',
  roll_eyes: '🙄',
  grimacing: '😬',
  zipper_mouth_face: '🤐',

  // Gestures
  '+1': '👍',
  thumbsup: '👍',
  '-1': '👎',
  thumbsdown: '👎',
  ok_hand: '👌',
  pinched_fingers: '🤌',
  pinching_hand: '🤏',
  v: '✌️',
  crossed_fingers: '🤞',
  love_you_gesture: '🤟',
  metal: '🤘',
  call_me_hand: '🤙',
  point_left: '👈',
  point_right: '👉',
  point_up_2: '👆',
  middle_finger: '🖕',
  point_down: '👇',
  point_up: '☝️',
  raised_hand: '✋',
  raised_back_of_hand: '🤚',
  hand: '✋',
  vulcan_salute: '🖖',
  wave: '👋',
  clap: '👏',
  muscle: '💪',
  writing_hand: '✍️',
  pray: '🙏',
  fist: '✊',
  fist_oncoming: '👊',
  fist_left: '🤛',
  fist_right: '🤜',

  // Hearts & Emotions
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  brown_heart: '🤎',
  white_heart: '🤍',
  broken_heart: '💔',
  two_hearts: '💕',
  revolving_hearts: '💞',
  heartbeat: '💓',
  heartpulse: '💗',
  sparkling_heart: '💖',
  cupid: '💘',
  gift_heart: '💝',
  heart_decoration: '💟',
  heavy_heart_exclamation: '❣️',
  love_letter: '💌',
  fire: '🔥',
  star: '⭐',
  star2: '🌟',
  sparkles: '✨',
  boom: '💥',
  collision: '💥',
  zap: '⚡',
  sunny: '☀️',
  rainbow: '🌈',
  cloud: '☁️',

  // Objects
  rocket: '🚀',
  tada: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',
  birthday: '🎂',
  gift: '🎁',
  trophy: '🏆',
  medal_sports: '🏅',
  medal_military: '🎖️',
  first_place_medal: '🥇',
  second_place_medal: '🥈',
  third_place_medal: '🥉',
  bell: '🔔',
  no_bell: '🔕',
  bulb: '💡',
  flashlight: '🔦',
  wrench: '🔧',
  hammer: '🔨',
  nut_and_bolt: '🔩',
  gear: '⚙️',
  link: '🔗',
  key: '🔑',
  lock: '🔒',
  unlock: '🔓',
  envelope: '✉️',
  email: '📧',
  memo: '📝',
  pencil2: '✏️',
  black_nib: '✒️',
  book: '📖',
  books: '📚',
  page_facing_up: '📄',
  newspaper: '📰',
  calendar: '📅',
  clipboard: '📋',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  bar_chart: '📊',
  moneybag: '💰',
  dollar: '💵',
  credit_card: '💳',
  computer: '💻',
  keyboard: '⌨️',
  desktop_computer: '🖥️',
  printer: '🖨️',
  mouse: '🖱️',
  cd: '💿',
  dvd: '📀',
  floppy_disk: '💾',
  phone: '📱',
  telephone_receiver: '📞',
  camera: '📷',
  camera_flash: '📸',
  video_camera: '📹',
  movie_camera: '🎥',
  clapper: '🎬',
  tv: '📺',
  microphone: '🎤',
  headphones: '🎧',
  musical_note: '🎵',
  notes: '🎶',
  guitar: '🎸',
  violin: '🎻',
  piano: '🎹',
  drum: '🥁',
  trumpet: '🎺',

  // Symbols
  white_check_mark: '✅',
  ballot_box_with_check: '☑️',
  heavy_check_mark: '✔️',
  x: '❌',
  negative_squared_cross_mark: '❎',
  heavy_multiplication_x: '✖️',
  heavy_plus_sign: '➕',
  heavy_minus_sign: '➖',
  heavy_division_sign: '➗',
  curly_loop: '➰',
  loop: '➿',
  question: '❓',
  grey_question: '❔',
  exclamation: '❗',
  grey_exclamation: '❕',
  bangbang: '‼️',
  interrobang: '⁉️',
  100: '💯',
  warning: '⚠️',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  copyright: '©️',
  registered: '®️',
  tm: '™️',
  recycle: '♻️',
  information_source: 'ℹ️',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrow_left: '⬅️',
  arrow_right: '➡️',
  arrow_upper_left: '↖️',
  arrow_upper_right: '↗️',
  arrow_lower_left: '↙️',
  arrow_lower_right: '↘️',
  leftwards_arrow_with_hook: '↩️',
  arrow_right_hook: '↪️',
  arrows_clockwise: '🔃',
  arrows_counterclockwise: '🔄',
  back: '🔙',
  end: '🔚',
  on: '🔛',
  soon: '🔜',
  top: '🔝',

  // Animals
  dog: '🐶',
  cat: '🐱',
  mouse2: '🐭',
  hamster: '🐹',
  rabbit: '🐰',
  fox_face: '🦊',
  bear: '🐻',
  panda_face: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey_face: '🐵',
  see_no_evil: '🙈',
  hear_no_evil: '🙉',
  speak_no_evil: '🙊',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  baby_chick: '🐤',
  hatching_chick: '🐣',
  hatched_chick: '🐥',
  duck: '🦆',
  eagle: '🦅',
  owl: '🦉',
  bat: '🦇',
  wolf: '🐺',
  horse: '🐴',
  unicorn: '🦄',
  bee: '🐝',
  bug: '🐛',
  butterfly: '🦋',
  snail: '🐌',
  shell: '🐚',
  beetle: '🐞',
  ant: '🐜',
  spider: '🕷️',
  spider_web: '🕸️',
  turtle: '🐢',
  snake: '🐍',
  lizard: '🦎',
  scorpion: '🦂',
  crab: '🦀',
  octopus: '🐙',
  squid: '🦑',
  shrimp: '🦐',
  tropical_fish: '🐠',
  fish: '🐟',
  blowfish: '🐡',
  dolphin: '🐬',
  shark: '🦈',
  whale: '🐳',
  whale2: '🐋',

  // Food & Drink
  apple: '🍎',
  green_apple: '🍏',
  pear: '🍐',
  tangerine: '🍊',
  lemon: '🍋',
  banana: '🍌',
  watermelon: '🍉',
  grapes: '🍇',
  strawberry: '🍓',
  melon: '🍈',
  cherries: '🍒',
  peach: '🍑',
  mango: '🥭',
  pineapple: '🍍',
  coconut: '🥥',
  kiwi_fruit: '🥝',
  tomato: '🍅',
  eggplant: '🍆',
  avocado: '🥑',
  carrot: '🥕',
  corn: '🌽',
  hot_pepper: '🌶️',
  cucumber: '🥒',
  leafy_green: '🥬',
  broccoli: '🥦',
  onion: '🧅',
  garlic: '🧄',
  mushroom: '🍄',
  potato: '🥔',
  sweet_potato: '🍠',
  bread: '🍞',
  croissant: '🥐',
  baguette_bread: '🥖',
  pretzel: '🥨',
  cheese: '🧀',
  egg: '🥚',
  cooking: '🍳',
  bacon: '🥓',
  pancakes: '🥞',
  hamburger: '🍔',
  fries: '🍟',
  pizza: '🍕',
  hotdog: '🌭',
  sandwich: '🥪',
  taco: '🌮',
  burrito: '🌯',
  sushi: '🍣',
  ramen: '🍜',
  stew: '🍲',
  curry: '🍛',
  rice: '🍚',
  rice_ball: '🍙',
  spaghetti: '🍝',
  cake: '🍰',
  doughnut: '🍩',
  cookie: '🍪',
  chocolate_bar: '🍫',
  candy: '🍬',
  lollipop: '🍭',
  ice_cream: '🍨',
  icecream: '🍦',
  pie: '🥧',
  coffee: '☕',
  tea: '🍵',
  sake: '🍶',
  champagne: '🍾',
  wine_glass: '🍷',
  cocktail: '🍸',
  tropical_drink: '🍹',
  beer: '🍺',
  beers: '🍻',
  clinking_glasses: '🥂',
  tumbler_glass: '🥃',
  cup_with_straw: '🥤',
  bubble_tea: '🧋',

  // Nature
  seedling: '🌱',
  evergreen_tree: '🌲',
  deciduous_tree: '🌳',
  palm_tree: '🌴',
  cactus: '🌵',
  tulip: '🌷',
  cherry_blossom: '🌸',
  rose: '🌹',
  hibiscus: '🌺',
  sunflower: '🌻',
  blossom: '🌼',
  bouquet: '💐',
  four_leaf_clover: '🍀',
  shamrock: '☘️',
  fallen_leaf: '🍂',
  maple_leaf: '🍁',
  leaves: '🍃',

  // Weather
  sun_behind_cloud: '⛅',
  cloud_with_rain: '🌧️',
  thunder_cloud_and_rain: '⛈️',
  snowflake: '❄️',
  snowman: '⛄',
  wind_face: '🌬️',
  dash: '💨',
  droplet: '💧',
  ocean: '🌊',

  // People & Roles
  boy: '👦',
  girl: '👧',
  man: '👨',
  woman: '👩',
  older_man: '👴',
  older_woman: '👵',
  baby: '👶',
  angel: '👼',
  cop: '👮',
  dancer: '💃',
  man_dancing: '🕺',
  bride_with_veil: '👰',
  person_with_blond_hair: '👱',
  man_with_turban: '👳',
  construction_worker: '👷',
  princess: '👸',
  guardsman: '💂',
  detective: '🕵️',
  santa: '🎅',
  mrs_claus: '🤶',
  mage: '🧙',
  fairy: '🧚',
  vampire: '🧛',
  mermaid: '🧜',
  merman: '🧜‍♂️',
  elf: '🧝',
  genie: '🧞',
  zombie: '🧟',
  skull: '💀',
  ghost: '👻',
  alien: '👽',
  robot: '🤖',
  imp: '👿',
  smiling_imp: '😈',
  poop: '💩',
  hankey: '💩',

  // Activities
  soccer: '⚽',
  basketball: '🏀',
  football: '🏈',
  baseball: '⚾',
  tennis: '🎾',
  volleyball: '🏐',
  rugby_football: '🏉',
  golf: '⛳',
  ping_pong: '🏓',
  badminton: '🏸',
  ice_hockey: '🏒',
  lacrosse: '🥍',
  cricket_game: '🏏',
  goal_net: '🥅',
  ski: '🎿',
  skier: '⛷️',
  snowboarder: '🏂',
  ice_skate: '⛸️',
  skateboard: '🛹',
  swimmer: '🏊',
  surfer: '🏄',
  horse_racing: '🏇',
  running: '🏃',
  walking: '🚶',
  bicyclist: '🚴',
  mountain_bicyclist: '🚵',
  weight_lifting: '🏋️',
  wrestler: '🤼',
  boxing_glove: '🥊',
  martial_arts_uniform: '🥋',
  fishing_pole_and_fish: '🎣',
  dart: '🎯',
  bowling: '🎳',
  video_game: '🎮',
  game_die: '🎲',
  chess_pawn: '♟️',
  jigsaw: '🧩',
  performing_arts: '🎭',
  art: '🎨',

  // Vehicles & Transport
  car: '🚗',
  taxi: '🚕',
  bus: '🚌',
  trolleybus: '🚎',
  racing_car: '🏎️',
  police_car: '🚓',
  ambulance: '🚑',
  fire_engine: '🚒',
  minibus: '🚐',
  truck: '🚚',
  tractor: '🚜',
  motorcycle: '🏍️',
  bike: '🚲',
  scooter: '🛴',
  train: '🚆',
  tram: '🚊',
  metro: '🚇',
  monorail: '🚝',
  helicopter: '🚁',
  airplane: '✈️',
  small_airplane: '🛩️',
  ship: '🚢',
  sailboat: '⛵',
  speedboat: '🚤',
  anchor: '⚓',

  // Places
  house: '🏠',
  house_with_garden: '🏡',
  office: '🏢',
  post_office: '🏣',
  european_post_office: '🏤',
  hospital: '🏥',
  bank: '🏦',
  hotel: '🏨',
  school: '🏫',
  convenience_store: '🏪',
  department_store: '🏬',
  factory: '🏭',
  japanese_castle: '🏯',
  european_castle: '🏰',
  tent: '⛺',
  stadium: '🏟️',
  ferris_wheel: '🎡',
  roller_coaster: '🎢',
  carousel_horse: '🎠',
  fountain: '⛲',
  beach_umbrella: '🏖️',
  desert: '🏜️',
  desert_island: '🏝️',
  mountain: '⛰️',
  snow_capped_mountain: '🏔️',
  mount_fuji: '🗻',
  camping: '🏕️',
  volcano: '🌋',
  earth_africa: '🌍',
  earth_americas: '🌎',
  earth_asia: '🌏',
  globe_with_meridians: '🌐',
  world_map: '🗺️',
  japan: '🗾',
  compass: '🧭',
  statue_of_liberty: '🗽',

  // Time
  watch: '⌚',
  clock1: '🕐',
  clock2: '🕑',
  clock3: '🕒',
  clock4: '🕓',
  clock5: '🕔',
  clock6: '🕕',
  clock7: '🕖',
  clock8: '🕗',
  clock9: '🕘',
  clock10: '🕙',
  clock11: '🕚',
  clock12: '🕛',
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  alarm_clock: '⏰',
  stopwatch: '⏱️',
  timer_clock: '⏲️',

  // Flags
  checkered_flag: '🏁',
  triangular_flag_on_post: '🚩',
  crossed_flags: '🎌',
  black_flag: '🏴',
  white_flag: '🏳️',
  rainbow_flag: '🏳️‍🌈',
  pirate_flag: '🏴‍☠️',

  // GitHub-specific
  octocat: '🐙',
  shipit: '🐿️',
  neckbeard: '🧔',
  trollface: '👹',
  bowtie: '🎀',
  suspect: '🕵️',
  hurtrealbad: '😖',
  goberserk: '😤',
  godmode: '😎',
  finnadie: '💀',
  feelsgood: '😊',
  rage1: '😤',
  rage2: '😤',
  rage3: '😤',
  rage4: '😤',
};

/**
 * Jemoji Plugin implementation
 */
export class JemojiPlugin implements Plugin {
  name = 'jemoji';

  register(renderer: Renderer, _site: Site): void {
    // Register the emojify filter
    renderer.getLiquid().registerFilter('emojify', (input: string) => {
      return emojify(input);
    });
  }
}

/**
 * Convert GitHub-style emoji codes to actual emoji characters
 * @param input String containing emoji codes like :smile:
 * @returns String with emoji codes replaced by actual emoji
 */
export function emojify(input: string): string {
  if (!input) return '';

  // Match :emoji_name: patterns
  // Emoji names can contain letters, numbers, underscores, plus signs, and minus signs
  return String(input).replace(/:([a-zA-Z0-9_+-]+):/g, (match, emojiName) => {
    const emoji = EMOJI_MAP[emojiName.toLowerCase()];
    return emoji || match; // Return original if not found
  });
}

/**
 * Get the emoji character for a given emoji name
 * @param name Emoji name without colons (e.g., 'smile')
 * @returns Emoji character or undefined if not found
 */
export function getEmoji(name: string): string | undefined {
  return EMOJI_MAP[name.toLowerCase()];
}

/**
 * Check if a given emoji name exists
 * @param name Emoji name to check
 * @returns True if emoji exists
 */
export function hasEmoji(name: string): boolean {
  return name.toLowerCase() in EMOJI_MAP;
}

/**
 * Get all available emoji names
 * @returns Array of emoji names
 */
export function getEmojiNames(): string[] {
  return Object.keys(EMOJI_MAP);
}
